---
title: "Cristobal - FA8"
output: html_document
date: "2023-04-30"
---

1. In Example 16.3 with ğœ† = 4 per minute, use R to obtain:
(a) P(T â‰¤ 0.25) = P(time between submissions is at most 15 seconds)
```
p <- pexp(.25,4)
cat("Probability is: ", p)

```
(b) P(T > 0.5) = P(time between submissions is greater than 30 seconds)
```
p <- pexp(.5,4)
cat("Probability is: ", p)

```
(c) P(0.25 < T < 1) = P(time between submissions is between 15 seconds
and 1 minute).

```
p1 <- pexp(.25,4)
p2 <- pexp(1,4)
p1
p2
cat("Probability is: ", p2-p1)

```

3. The average rate of job submissions in a computer center is 2 per minute. If
it can be assumed that the number of submissions per minute has a Poisson
distribution, calculate the probability that:
(a) more than two jobs will arrive in a minute
```
pmore <- 1 - ppois(2,2)
cat("Probability that more than two jobs will arrive: ", pmore)
```
(b) at least 30 seconds will elapse between any two jobs;
(c) less than 30 seconds will elapse between jobs;
(d) a job will arrive in the next 30 seconds, if no jobs have arrived in the last
30 seconds.

7. A website receives an average of 15 visits per hour, which arrive following a
Poisson distribution.
(a) Calculate the probability that at least 10 minutes will elapse without a
visit.
(b) What is the probability that in any hour, there will be less than eight visits?
(c) Suppose that 15 minutes have elapsed since the last visit, what is the prob-
ability that a visit will occur in the next 15 minutes.
(d) Calculate the top quartile, and explain what it means.